cadastros/urls.py
from django.urls import path

from .views import CadastrosView, CategoriaList, CategoriaCreate, CategoriaEdit, CategoriaDelete
from .views import SubcategoriaList, SubcategoriaCreate, SubcategoriaEdit, SubcategoriaDelete
from .views import FornecedorList, FornecedorCreate, FornecedorEdit, FornecedorDelete

app_name = 'cad_menu'

urlpatterns = [
    path('', CadastrosView.as_view(), name='cad_menu'),
    path('categorias', CategoriaList.as_view(), name='categoria_list'),
    path('categorias/<int:pk>/', CategoriaEdit.as_view(), name='categoria_edit'),
    path('categorias/<int:pk>/delete/', CategoriaDelete.as_view(), name='categoria_delete'),
    path('categorias/insert/', CategoriaCreate.as_view(), name='categoria_create'),
    path('subcategorias',SubcategoriaList.as_view(), name='subcategoria_list'),
    path('subcategorias/<int:pk>/', SubcategoriaEdit.as_view(), name='subcategoria_edit'),
    path('subcategorias/<int:pk>/delete/', SubcategoriaDelete.as_view(), name='subcategoria_delete'),
    path('subcategorias/insert/', SubcategoriaCreate.as_view(), name='subcategoria_create'),
    path('fornecedores',FornecedorList.as_view(), name='fornecedor_list'),
    path('fornecedores/<int:pk>/', FornecedorEdit.as_view(), name='fornecedor_edit'),
    path('fornecedores/<int:pk>/delete/', FornecedorDelete.as_view(), name='fornecedor_delete'),
    path('fornecedores/insert/', FornecedorCreate.as_view(), name='fornecedor_create'),
]

pages/urls.py
from django.urls import path

from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('cat/<int:cat>/', views.HomePageView.as_view(), name='home_cat'),
    path('cat/<int:cat>/sub/<int:sub>/', views.HomePageView.as_view(), name='home_sub'),
]

website/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('pages.urls', namespace='pages')),
    path('cadastros/', include('cadastros.urls', namespace='cadastros')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cadastros/models.py
from django.db import models
#from stdimage.models import StdImageField

class Categoria(models.Model):
    nome = models.CharField('nome', max_length=45)
    informacoes = models.TextField('informacoes')
    ordem_menu = models.PositiveSmallIntegerField('ordem_menu', null=False, default=0)
    foto_categoria = models.ImageField(null=True, blank=True, upload_to='categorias')
    foto_topo = models.ImageField(null=True, blank=True, upload_to='categorias')
    #foto_categoria = models.ImageField(null=True, blank=True, upload_to='categorias/%Y/%m/%d')

    class Meta:
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'
        ordering = ['nome']

    def __str__(self):
        return self.nome


class Subcategoria(models.Model):
      categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE,null=True)

      nome = models.CharField(max_length=45)

      class Meta:
          verbose_name = 'Subcategoria'
          verbose_name_plural = 'Subcategorias'
          ordering = ['nome']

      def __str__(self):
          return self.nome

class Fornecedor(models.Model):
    subcategoria = models.ForeignKey(Subcategoria, on_delete=models.CASCADE, null= True)
    nome = models.CharField('nome', max_length=45)
    endereco = models.CharField('endereco',max_length=255, blank = True)
    contato= models.CharField('contato', max_length=45, null=True)
    informacoes = models.TextField(blank = True)

    class Meta:
        verbose_name = 'Fornecedor'
        verbose_name_plural = 'Fornecedores'
        ordering = ['nome']

    def __str__(self):
        return self.nome



"""
EDUCACAO  (Categoria)

   > AULAS PARTICULARES MATEMATICA   (Subcategoria)
        > Douglas Maioli  (Fornecedor)

   > AULAS PARTICULARES INGLES
"""

cadastros/forms.py
from django import forms

from .models import Categoria, Subcategoria, Fornecedor

class CategoriaForm(forms.ModelForm):

    class Meta:
        model = Categoria
        fields = ('nome', 'informacoes', 'ordem_menu', 'foto_categoria', 'foto_topo', )

class SubcategoriaForm(forms.ModelForm):

    class Meta:
        model = Subcategoria
        fields = ('nome', 'categoria', )

class FornecedorForm(forms.ModelForm):

    class Meta:
        model = Fornecedor
        fields = ('nome', 'subcategoria', 'endereco', 'contato', 'informacoes', )

cadastros/views.py
from django.views.generic import TemplateView, ListView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy

from braces.views import GroupRequiredMixin

from .forms import CategoriaForm, SubcategoriaForm, FornecedorForm
from .models import Categoria, Subcategoria, Fornecedor
import services.categoria_service as CategoriaService

#class CadastrosView(GroupRequiredMixin, LoginRequiredMixin, TemplateView):
class CadastrosView(LoginRequiredMixin, TemplateView):

    template_name = 'cadastros/index.html'
    #group_required = 'admin_users'  # se descomentar essas linhas
    #redirect_field_name = '/'       # essa tela nao tá aparecendo nem para admin

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cat_db'] = CategoriaService.get_menubar()
        return context


# Categoria
# --------------------------

class CategoriaList(GroupRequiredMixin, LoginRequiredMixin, ListView):

    model = Categoria
    form_class = CategoriaForm
    context_object_name = 'db'
    template_name = 'cadastros/categoria/list.html'
    group_required = 'admin_users'
    redirect_field_name = '/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cat_db'] = CategoriaService.get_menubar()
        return context

class CategoriaCreate(GroupRequiredMixin, LoginRequiredMixin, CreateView):

    model = Categoria
    form_class = CategoriaForm
    template_name = 'cadastros/categoria/form.html'
    success_url = reverse_lazy('cadastros:categoria_list')
    group_required = 'admin_users'
    redirect_field_name = '/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cat_db'] = CategoriaService.get_menubar()
        return context

class CategoriaEdit(GroupRequiredMixin, LoginRequiredMixin, UpdateView):

    model = Categoria
    form_class = CategoriaForm
    template_name = 'cadastros/categoria/form.html'
    success_url = reverse_lazy('cadastros:categoria_list')
    group_required = 'admin_users'
    redirect_field_name = '/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cat_db'] = CategoriaService.get_menubar()
        return context

class CategoriaDelete(GroupRequiredMixin, LoginRequiredMixin, DeleteView):

    model = Categoria
    template_name = 'cadastros/categoria/confirm_delete.html'
    success_url = reverse_lazy('cadastros:categoria_list')
    group_required = 'admin_users'
    redirect_field_name = '/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cat_db'] = CategoriaService.get_menubar()
        return context


# Subcategoria
# --------------------------

class SubcategoriaList(GroupRequiredMixin, LoginRequiredMixin, ListView):

    model = Subcategoria
    form_class = SubcategoriaForm
    context_object_name = 'db'
    template_name = 'cadastros/subcategoria/list.html'
    group_required = 'admin_users'
    redirect_field_name = '/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cat_db'] = CategoriaService.get_menubar()
        return context

class SubcategoriaCreate(GroupRequiredMixin, LoginRequiredMixin, CreateView):

    model = Subcategoria
    form_class = SubcategoriaForm
    template_name = 'cadastros/subcategoria/form.html'
    success_url = reverse_lazy('cadastros:subcategoria_list')
    group_required = 'admin_users'
    redirect_field_name = '/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cat_db'] = CategoriaService.get_menubar()
        return context

class SubcategoriaEdit(GroupRequiredMixin, LoginRequiredMixin, UpdateView):

    model = Subcategoria
    form_class = SubcategoriaForm
    template_name = 'cadastros/subcategoria/form.html'
    success_url = reverse_lazy('cadastros:subcategoria_list')
    group_required = 'admin_users'
    redirect_field_name = '/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cat_db'] = CategoriaService.get_menubar()
        return context

class SubcategoriaDelete(GroupRequiredMixin, LoginRequiredMixin, DeleteView):

    model = Subcategoria
    template_name = 'cadastros/subcategoria/confirm_delete.html'
    success_url = reverse_lazy('cadastros:subcategoria_list')
    group_required = 'admin_users'
    redirect_field_name = '/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cat_db'] = CategoriaService.get_menubar()
        return context


# Fornecedor
# --------------------------

class FornecedorList(GroupRequiredMixin, LoginRequiredMixin, ListView):

    model = Fornecedor
    form_class = FornecedorForm
    context_object_name = 'db'
    template_name = 'cadastros/fornecedor/list.html'
    group_required = 'admin_users'
    redirect_field_name = '/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cat_db'] = CategoriaService.get_menubar()
        return context

class FornecedorCreate(GroupRequiredMixin, LoginRequiredMixin, CreateView):

    model = Fornecedor
    form_class = FornecedorForm
    template_name = 'cadastros/fornecedor/form.html'
    success_url = reverse_lazy('cadastros:fornecedor_list')
    group_required = 'admin_users'
    redirect_field_name = '/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cat_db'] = CategoriaService.get_menubar()
        return context

class FornecedorEdit(GroupRequiredMixin, LoginRequiredMixin, UpdateView):

    model = Fornecedor
    form_class = FornecedorForm
    template_name = 'cadastros/fornecedor/form.html'
    success_url = reverse_lazy('cadastros:fornecedor_list')
    group_required = 'admin_users'
    redirect_field_name = '/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cat_db'] = CategoriaService.get_menubar()
        return context

class FornecedorDelete(GroupRequiredMixin, LoginRequiredMixin, DeleteView):

    model = Fornecedor
    template_name = 'cadastros/fornecedor/confirm_delete.html'
    success_url = reverse_lazy('cadastros:fornecedor_list')
    group_required = 'admin_users'
    redirect_field_name = '/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cat_db'] = CategoriaService.get_menubar()
        return context

templates/cadastros/subcategoria/confirm_delete.html
{% extends 'base.html' %}
{% block content %}
<div class="col-12 m-auto pt-3 text-left">
    <h3>Subcategorias</h3>
</div>
<div class="container">
    <div class="row"></div>
    <br />
    <div class="row">
        <div class="col-md-2 col-xs-2 col-sm-2"></div>
        <div class="col-md-10 col-xs-10 col-sm-10">
            <form method="post">
                {% csrf_token %}
                <div class="form-row">
                    <div class="alert alert-warning mt-5">
                        Você deseja mesmo excluir {{ object }}?
                    </div>
                </div>
                <div class="mt-3">
                    <button type="submit" class="btn btn-success">Sim</button>
                    <a href="{% url 'cadastros:subcategoria_list' %}" class="btn btn-danger ml-3">Não</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/cadastros/subcategoria/form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div class="col-12 m-auto pt-3 text-left">
    <h3>Subcategorias</h3>
</div>

<div class="col-12 m-auto pt-4">
    <form name="form" id="form" action="" method='post'>
        {% csrf_token %}
        {{ form|crispy }}
        <div class="mt-5 mb-3">
            <button type="submit" class="btn btn-success">Salvar</button>
            <a href="{% url 'cadastros:subcategoria_list' %}" class="btn btn-danger ml-3">Cancelar</a>
        </div>
    </form>
</div>    

{% endblock %}

templates/cadastros/subcategoria/list.html
{% extends 'base.html' %}

{% block content %}

<div class="col-12 m-auto pt-3 text-left">
  <h3>Subcategorias</h3>
</div>

<div class="col-12 m-auto text-right">
    <a href="{% url 'cadastros:cad_menu' %}" class="btn btn-info mr-2" style="width: 100px">Voltar</a>
    <a href="{% url 'cadastros:subcategoria_create' %}" class="btn btn-success" style="width: 100px">Adicionar</a>
</div>

<div class="col-12 m-auto pt-4">
  <table class="table table-sm">
      <thead class="thead-light">
          <tr>
              <th scope="col">Nome</th>
              <th scope="col">Categoria</th>
              <th scope="col" style="width: 60px"></th>
          </tr>
      </thead>
      <tbody>
          {% for dbs in db %}
              <tr>
                  <td scope="row" class="align-middle">{{ dbs.nome }}</td>
                  <td scope="row" class="align-middle">{{ dbs.categoria.nome }}</td>
                  <td scope="row">
                      <a href="{% url 'cadastros:subcategoria_edit' dbs.id %}" class="pr-1"><i class="fas fa-edit text-info"></i></a>
                      <a href="{% url 'cadastros:subcategoria_delete' dbs.id %}"><i class="fas fa-trash text-danger"></i></a>
                  </td>
              </tr>
          {% endfor %}
      </tbody>
  </table>
</div>    

{% endblock %}