cadastros/urls.py
from django.urls import path

from .views import CadastrosView, CategoriaList, CategoriaCreate, CategoriaEdit, CategoriaDelete
from .views import SubcategoriaList, SubcategoriaCreate, SubcategoriaEdit, SubcategoriaDelete
from .views import FornecedorList, FornecedorCreate, FornecedorEdit, FornecedorDelete

app_name = 'cad_menu'

urlpatterns = [
    path('', CadastrosView.as_view(), name='cad_menu'),
    path('categorias', CategoriaList.as_view(), name='categoria_list'),
    path('categorias/<int:pk>/', CategoriaEdit.as_view(), name='categoria_edit'),
    path('categorias/<int:pk>/delete/', CategoriaDelete.as_view(), name='categoria_delete'),
    path('categorias/insert/', CategoriaCreate.as_view(), name='categoria_create'),
    path('subcategorias',SubcategoriaList.as_view(), name='subcategoria_list'),
    path('subcategorias/<int:pk>/', SubcategoriaEdit.as_view(), name='subcategoria_edit'),
    path('subcategorias/<int:pk>/delete/', SubcategoriaDelete.as_view(), name='subcategoria_delete'),
    path('subcategorias/insert/', SubcategoriaCreate.as_view(), name='subcategoria_create'),
    path('fornecedores',FornecedorList.as_view(), name='fornecedor_list'),
    path('fornecedores/<int:pk>/', FornecedorEdit.as_view(), name='fornecedor_edit'),
    path('fornecedores/<int:pk>/delete/', FornecedorDelete.as_view(), name='fornecedor_delete'),
    path('fornecedores/insert/', FornecedorCreate.as_view(), name='fornecedor_create'),
]

pages/urls.py
from django.urls import path

from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('cat/<int:cat>/', views.HomePageView.as_view(), name='home_cat'),
    path('cat/<int:cat>/sub/<int:sub>/', views.HomePageView.as_view(), name='home_sub'),
]

website/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('pages.urls', namespace='pages')),
    path('cadastros/', include('cadastros.urls', namespace='cadastros')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <header>
        
            {% if is_home %}
            <div class="container-fluid">
                <!-- Logo -->
                <div class="row">
                    <div class="col-md-12">
                        <a href="">
                            <img src="{% static 'images/logo.png' %}" class="img-fluid d-block mx-auto pt-2 pb-2"  width="100" height="100" alt="">
                        </a>
                    </div>
                </div>
                <!-- Slogan -->
                <div class="row">
                    <div class="col-md-12 bg-dark">
                        <h6 class="text-white text-center mt-2 mb-2">IndiqueSim - Indicação de serviços e produtos</h6>
                    </div>
                </div>
            </div>        
                     <!-- Carousel -->
            <div id="carousel-controle" class="carousel slide" data-ride="carousel">
                <!-- Inner -->
                <div class="carousel-inner">
                    <!-- Itens do Carousel -->
                    <div class="carousel-item active">
                        <img src="{% static 'images/carousel-food.jpg' %}" class="img-fluid d-block" alt="">
                    </div>
                    <div class="carousel-item">
                        <img src="{% static 'images/carousel-automotive.jpg' %}" class="img-fluid d-block" alt="">
                    </div>
                    <div class="carousel-item">
                        <img src="{% static 'images/carousel-beauty.jpg' %}" class="img-fluid d-block" alt="">
                    </div>
                    <div class="carousel-item">
                        <img src="{% static 'images/carousel-community.jpg' %}" class="img-fluid d-block" alt="">
                    </div>
                    <div class="carousel-item">
                        <img src="{% static 'images/carousel-maintenance.jpg' %}" class="img-fluid d-block" alt="">
                    </div>
                    <div class="carousel-item">
                        <img src="{% static 'images/carousel-fashion.jpg' %}" class="img-fluid d-block" alt="">
                    </div>
                    <div class="carousel-item">
                        <img src="{% static 'images/carousel-office.jpg' %}" class="img-fluid d-block" alt="">
                    </div>
                    <div class="carousel-item">
                        <img src="{% static 'images/carousel-pets.jpg' %}" class="img-fluid d-block" alt="">
                    </div>
                </div> <!-- Fim Carousel Inner -->
                <!-- Controles -->
                <a href="#carousel-controle" class="carousel-control-prev" data-slide="prev">
                    <i class="fas fa-chevron-left fa-3x"></i>
                </a>
                <a href="#carousel-controle" class="carousel-control-next" data-slide="next">
                    <i class="fas fa-chevron-right fa-3x"></i>
                </a>
            </div>
            {% else %}
                <img src="/media/{{ categoria_foto }}" class="img-fluid" style="width: 100%" alt="">
            {% endif %}
        

        <!--
        {% for dbs in cat_db %}

            {% if dbs.foto_categoria %}
                <img src="/media/{{ dbs.foto_categoria }}" class="img-fluid" alt="">
            {% else %}
                <img src="{% static 'images/no_image.jpg' %}" class="img-fluid" alt="">
            {% endif %}


            ///
            <a href="{% url 'pages:home' %}">
                <img src="{% static 'images/topo.jpg' %}" style="width: 100%" class="img-fluid" alt="Imagem responsiva">
            </a>
            ///

        {% endfor %}
        -->

        <nav class="navbar navbar-expand-lg navbar-dark bg-dark justify-content-center">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
              <ul class="navbar-nav mx-auto">
                {% for dbs in cat_db %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'pages:home_cat' dbs.id %}">{{ dbs.nome }}</a>
                    </li>
                {% endfor %}
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_logout' %}">Sair</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'cadastros:cad_menu' %}">Admin</a>
                    </li>
                {% endif %}    
              </ul>
            </div>
        </nav>
    </header>
    {% if messages %}
    <div class="container messages">
        {% for message in messages %}
        <div class="alert alert-info alert-dismissible fade show" role="alert">
            {{ message }}
        </div>
        {% endfor %}
    </div>
    {% endif %}

    <main class="container">
        {% block content %}
        {% endblock %}
    </main>
     <!-- Rodapé -->
     <footer class="bg-dark">
        <div class="container-footer mt-5">
            <div class="row">
                <div class="col-md-12 p-4">
                    <h5 class="text-white">Sobre</h5>
                    <p class="text-white">O IndiqueSim é o guia de serviços e produtos para a sua casa.
                        O nosso objetivo é disponibilizar na palma da mão, os fornecedores mais qualificados
                        de forma que você economize tempo e dinheiro na busca por um profissional ou
                        produto que atenda a sua necessidade. Então, aproveite essa facilidade!</p>
                </div>
            </div>
        </div>
        <hr class="divisor">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <p class="text-center text-white">Indique Sim 2021 - Todos os direitos reservados.</p>
                </div>
            </div>
        </div>
    </footer> <!-- Fim Rodapé -->


    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <script src="{% static 'js/javascript.js' %}"></script>
</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Prestadores de Serviço{% endblock %}

{% block content %}
  <div class="row mt-3">
    {% for dbs in cat_db %}

      {% if forloop.counter0|divisibleby:3 %}
          </div>
        </div>
        {% if forloop.last %}
          <div class="col-12 mt-2 rounded" style="background-color:#f1eee4">
        {% else %}
          <div class="col-12 mt-2 mb-4 rounded" style="background-color:#f1eee4">
        {% endif %}
        <div class="row p-3">
      {% endif %}

      <div class="col-4 text-center grow">
        <a href="{% url 'pages:home_cat' dbs.id %}">
          {% if dbs.foto_categoria %}
            <img src="/media/{{ dbs.foto_categoria }}" class="rounded-circle img-fluid" alt="">
          {% else %}
            <img src="{% static 'images/no_image.jpg' %}" class="rounded-circle img-fluid" alt="">
          {% endif %}
        </a>
        <h6 class="mt-2">{{dbs.nome}}</h6>
        <p style="line-height: 1.1"><small class="text-muted">{{ dbs.informacoes }}</small></p>
      </div>

    {% endfor %}
  </div>
{% endblock %}

templates/lista_fornecedor.html
{% extends 'base.html' %}

{% block title %}Prestadores de Serviço{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-5 col-sm-3 mt-5 p-0">
      <div class="list-group">
        <span class="list-group-item list-group-item-action subcatmenu bg-secondary bg-dark text-white">{{ categoria_nome }}</span>
        {% for dbs in sub_db %}
          {% if dbs.id == sub_pk %}
            <a href="{% url 'pages:home_sub' dbs.categoria.id dbs.id %}" class="list-group-item list-group-item-action active subcatmenu">{{ dbs.nome }}</a>
          {% else %}
            <a href="{% url 'pages:home_sub' dbs.categoria.id dbs.id %}" class="list-group-item list-group-item-action subcatmenu">{{ dbs.nome }}</a>
          {% endif %}
        {% endfor %}
      </div>
    </div>
    <div class="col-7 col-sm-9 mt-4 p-0">
      <ul class="list-group list-group-flush">
        {% for dbs in db %}
          <li class="list-group-item">
            <h4>{{ dbs.nome }}</h4>
            <div>Endereço: {{ dbs.endereco }}</div>
            <div>Contato: {{ dbs.contato }}</div>
            <div>Informações: {{ dbs.informacoes }}</div>
          </li>
        {% endfor %}
      </ul>
      {% if is_paginated %}
      {% include "pagination.html" with page=page_obj %}
      {% endif %}
    </div>
{% endblock %}

templates/pagination.html
<div class="text-center mb-3 paginacao">
    {% if page.has_previous %}
    <a href="?page={{ page.previous_page_number }}"><i class="fas fa-caret-square-left"></i></a>
    {% else %}
    <i class="fas fa-caret-square-left text-secondary"></i>
    {% endif %}
    Página {{ page.number }}/{{ page.paginator.num_pages }}
    {% if page.has_next %}
    <a href="?page={{ page.next_page_number }}"><i class="fas fa-caret-square-right"></i></a>
    {% else %}
    <i class="fas fa-caret-square-right text-secondary"></i>
    {% endif %}
</div>